#### AULA 03

- Bibliotecas PANDAS e NUMPY

In [7]:
import pandas as pd
import numpy as np

In [8]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]

## criar arrays para que possamos manipular os dados

array_quantidade = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_quantidade * array_precos
print(faturamento)

[  30   25   42 1000]

In [9]:
quantidade_produtos = [3,5,6,10]
precos_produtos = [10,5,7,100]
nomes_produtos = ['pastel', 'caçulinha', 'refrigerante', 'combo']

## criar arrays para que possamos manipular os dados

array_quantidade = np.array(quantidade_produtos)
array_precos = np.array(precos_produtos)

faturamento = array_quantidade * array_precos
for nome, preco in zip(nomes_produtos, faturamento):
    print(f'{nome} : R${preco}')

pastel : R$30
caçulinha : R$25
refrigerante : R$42
combo : R$1000

In [10]:
# Lista com o nome de 10 produtos
produtos = [
    "Arroz",
    "Feijão",
    "Macarrão",
    "Óleo",
    "Açúcar",
    "Café",
    "Leite",
    "Sabão em Pó",
    "Detergente",
    "Papel Higiênico"
]

# Lista com os preços de custo
preco_custo = [
    18.50,
    7.20,
    4.10,
    5.80,
    3.90,
    12.50,
    4.80,
    10.00,
    2.30,
    15.00
]

# Lista com os preços de venda
preco_venda = [
    24.90,
    9.50,
    5.90,
    7.90,
    5.50,
    16.90,
    6.50,
    14.90,
    3.90,
    19.90
]

array_produtos = np.array(produtos)
array_custo = np.array(preco_custo)
array_venda = np.array(preco_venda)

lucro = array_venda - array_custo
for nome, valor, custeio in zip(produtos, lucro, preco_custo):
    print(f'O lucro do {nome} foi de R${valor:.2f} e o produto custou R${custeio}')
    
lucro_total = np.sum(lucro)
print(f'O lucro total é de R$ {lucro_total}')

O lucro do Arroz foi de R$6.40 e o produto custou R$18.5
O lucro do Feijão foi de R$2.30 e o produto custou R$7.2
O lucro do Macarrão foi de R$1.80 e o produto custou R$4.1
O lucro do Óleo foi de R$2.10 e o produto custou R$5.8
O lucro do Açúcar foi de R$1.60 e o produto custou R$3.9
O lucro do Café foi de R$4.40 e o produto custou R$12.5
O lucro do Leite foi de R$1.70 e o produto custou R$4.8
O lucro do Sabão em Pó foi de R$4.90 e o produto custou R$10.0
O lucro do Detergente foi de R$1.60 e o produto custou R$2.3
O lucro do Papel Higiênico foi de R$4.90 e o produto custou R$15.0
O lucro total é de R$ 31.7

In [11]:
## ignorar barras  invertidas ('r)
## .\ - quer dizer que existe caminho ainda na pasta 

df = pd.read_csv(r'.\data\dataset_aula1_numpy_pandas.csv')

df.head()
#df.head(total de linhas) - se quiser ver mais linhas

   id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
0            1  Montagem          72.62          41.77           111      0
1            2  Usinagem          81.65          34.08           128      0
2            3  Usinagem          68.87          39.44           159      0
3            4  Usinagem          66.84          34.52            98      0
4            5  Usinagem          66.23          31.57            94      0

In [12]:
df.tail() #mostra as 5 ultimas

#df.tail(numero de colunas) se quiser ver mais linhas

    id_registro     setor  temperatura_c  tempo_ciclo_s  producao_dia  falha
35           36  Usinagem          68.47          36.87            87      0
36           37  Inspeção          75.62          30.78           125      1
37           38  Usinagem          78.50          36.39            90      0
38           39  Montagem          76.19          36.54           111      1
39           40  Montagem          68.64          34.88           102      0

In [13]:
df.shape ##saber o total de linhas e colunas

#nao se usa parenteses pois é um metodo (icone de chave de fenda); no caso de função é necessário o uso como o head ou tail

(40, 6)

In [14]:
df.columns # mostra o nome das colunas do df, tambem um metodo e nao é necessario o uso de parenteses

Index(['id_registro', 'setor', 'temperatura_c', 'tempo_ciclo_s',
       'producao_dia', 'falha'],
      dtype='str')

In [15]:
df.info() # necessario parenteses por ser uma função

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_registro    40 non-null     int64
 1   setor          40 non-null     str
 2   temperatura_c  40 non-null     float64
 3   tempo_ciclo_s  40 non-null     float64
 4   producao_dia   40 non-null     int64
 5   falha          40 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 2.3 KB

In [16]:

df.duplicated().sum()

np.int64(0)

In [17]:
# contar valores nulos
df.isna().sum()

id_registro      0
setor            0
temperatura_c    0
tempo_ciclo_s    0
producao_dia     0
falha            0
dtype: int64

In [18]:
df.describe()

       id_registro  temperatura_c  tempo_ciclo_s  producao_dia      falha
count    40.000000      40.000000      40.000000     40.000000  40.000000
mean     20.500000      72.525750      35.103250    116.400000   0.300000
std      11.690452       5.923691       3.918479     26.071696   0.464095
min       1.000000      60.310000      27.200000     80.000000   0.000000
25%      10.750000      68.597500      32.580000     92.750000   0.000000
50%      20.500000      73.425000      34.960000    111.000000   0.000000
75%      30.250000      76.310000      36.925000    136.750000   1.000000
max      40.000000      85.020000      47.450000    159.000000   1.000000

In [19]:
df = pd.read_csv(r'.\data\dataset_techshop_vendas.csv')

In [20]:
df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9

In [21]:
df.tail()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao
795,2024-12-27,Áudio,1128.44,4,Sul,Orgânico,4.6
796,2024-12-27,Acessórios,209.29,4,Sudeste,Google Ads,3.8
797,2024-12-28,Notebooks,7979.84,2,Sudeste,Google Ads,4.4
798,2024-12-28,Notebooks,4168.01,1,Nordeste,Instagram,4.1
799,2024-12-28,Acessórios,111.95,1,Sul,Google Ads,4.7

In [22]:
df.shape

(800, 7)

In [23]:
df.columns

Index(['data_pedido', 'categoria', 'preco_unitario', 'quantidade', 'regiao',
       'canal_marketing', 'avaliacao'],
      dtype='str')

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_pedido      800 non-null    str
 1   categoria        800 non-null    str
 2   preco_unitario   800 non-null    float64
 3   quantidade       800 non-null    int64
 4   regiao           800 non-null    str
 5   canal_marketing  800 non-null    str
 6   avaliacao        800 non-null    float64
dtypes: float64(2), int64(1), str(4)
memory usage: 70.9 KB

In [25]:
df.describe()

       preco_unitario  quantidade   avaliacao
count      800.000000  800.000000  800.000000
mean      2173.764038    2.237500    4.165500
std       2042.173946    1.306034    0.542658
min         20.070000    1.000000    2.400000
25%        249.837500    1.000000    3.800000
50%       1458.565000    2.000000    4.200000
75%       3707.427500    3.000000    4.600000
max       7979.840000    5.000000    5.000000

In [27]:
df.isna().sum()

data_pedido        0
categoria          0
preco_unitario     0
quantidade         0
regiao             0
canal_marketing    0
avaliacao          0
dtype: int64

In [ ]:
## Modelo para filtrar apenas as colunas desejadas

df[["data_pedido", "preco_unitario"]]

    data_pedido  preco_unitario
0    2024-01-01           36.20
1    2024-01-01          122.61
2    2024-01-02          151.19
3    2024-01-03         3399.16
4    2024-01-04         3180.94
..          ...             ...
795  2024-12-27         1128.44
796  2024-12-27          209.29
797  2024-12-28         7979.84
798  2024-12-28         4168.01
799  2024-12-28          111.95

[800 rows x 2 columns]

In [34]:
## Como criar uma nova coluna relacionando dados do dataframe

df['valor_produtos'] = np.where(df['preco_unitario']>=100,"Venda ok", "venda não ok")

df.head()

,data_pedido,categoria,preco_unitario,quantidade,regiao,canal_marketing,avaliacao,valor_produtos
0,2024-01-01,Acessórios,36.20,1,Sudeste,Instagram,3.3,venda não ok
1,2024-01-01,Acessórios,122.61,5,Sudeste,Orgânico,4.4,Venda ok
2,2024-01-02,Acessórios,151.19,4,Sul,Google Ads,4.6,Venda ok
3,2024-01-03,TVs,3399.16,2,Sudeste,Google Ads,4.1,Venda ok
4,2024-01-04,Smartphones,3180.94,2,Nordeste,Instagram,3.9,Venda ok