In [80]:
import pandas as pd

In [ ]:
##Abrir arquivo txt.

arquivo = open(r'data\dom_casmurro.txt', encoding = 'utf-8')

In [ ]:
#Ler arquivo txt.

texto = arquivo.read()

len(texto)

381375

In [ ]:
#Transformar o arquivo em uma lista

palavras = texto.split()

len(palavras)

palavras

['DOM',
 'CASMURRO',
 'POR',
 'MACHADO',
 'DE',
 'ASSIS',
 'DA',
 'ACADEMIA',
 'BRAZILEIRA',
 'H.',
 'GARNIER,',
 'LIVREIRO-EDITOR',
 'RUA',
 'MOREIRA',
 'CEZAR,',
 '71',
 'RIO',
 'DE',
 'JANEIRO',
 '6,',
 'RUE',
 'DES',
 'SAINTS-PÈRES,',
 '6',
 'PARIZ',
 'I',
 'Do',
 'titulo.',
 'Uma',
 'noite',
 'destas,',
 'vindo',
 'da',
 'cidade',
 'para',
 'o',
 'Engenho',
 'Novo,',
 'encontrei',
 'no',
 'trem',
 'da',
 'Central',
 'um',
 'rapaz',
 'aqui',
 'do',
 'bairro,',
 'que',
 'eu',
 'conheço',
 'de',
 'vista',
 'e',
 'de',
 'chapéo.',
 'Comprimentou-me,',
 'sentou-se',
 'ao',
 'pé',
 'de',
 'mim,',
 'falou',
 'da',
 'lua',
 'e',
 'dos',
 'ministros,',
 'e',
 'acabou',
 'recitando-me',
 'versos.',
 'A',
 'viagem',
 'era',
 'curta,',
 'e',
 'os',
 'versos',
 'póde',
 'ser',
 'que',
 'não',
 'fossem',
 'inteiramente',
 'maus.',
 'Succedeu,',
 'porém,',
 'que',
 'como',
 'eu',
 'estava',
 'cançado,',
 'fechei',
 'os',
 'olhos',
 'tres',
 'ou',
 'quatro',
 'vezes;',
 'tanto',
 'bastou',
 'para',
 'que',
 'elle',
 'interrompesse',
 'a',
 'leitura',
 'e',
 'mettesse',
 'os',
 'versos',
 'no',
 'bolso.',
 '--Continue,',
 'disse',
 'eu',
 'accordando.',
 '--Já',
 'acabei,',
 'murmurou',
 'elle.',
 '--São',
 'muito',
 'bonitos.',
 'Vi-lhe',
 'fazer',
 'um',
 'gesto',
 'para',
 'tiral-os',
 'outra',
 'vez',
 'do',
 'bolso,',
 'mas',
 'não',
 'passou',
 'do',
 'gesto;',
 'estava',
 'amuado.',
 'No',
 'dia',
 'seguinte',
 'entrou',
 'a',
 'dizer',
 'de',
 'mim',
 'nomes',
 'feios,',
 'e',
 'acabou',
 'alcunhando-me',
 '_Dom',
 'Casmurro._',
 'Os',
 'visinhos,',
 'que',
 'não',
 'gostam',
 'dos',
 'meus',
 'habitos',
 'reclusos',
 'e',
 'calados,',
 'deram',
 'curso',
 'á',
 'alcunha,',
 'que',
 'afinal',
 'pegou.',
 'Nem',
 'por',
 'isso',
 'me',
 'zanguei.',
 'Contei',
 'a',
 'anecdota',
 'aos',
 'amigos',
 'da',
 'cidade,',
 'e',
 'elles,',
 'por',
 'graça,',
 'chamam-me',
 'assim,',
 'alguns',
 'em',
 'bilhetes:',
 '«Dom',
 'Casmurro,',
 'domingo',
 'vou',
 'jantar',
 'com',
 'você.»--«Vou',
 'para',
 'Petropolis,',
 'Dom',
 'Casmurro;',
 'a',
 'casa',
 'é',
 'a',
 'mesma',
 'da',
 'Rhenania;',
 'vê',
 'se',
 'deixas',
 'essa',
 'caverna',
 'do',
 'Engenho',
 'Novo,',
 'e',
 'vae',
 'lá',
 'passar',
 'uns',
 'quinze',
 'dias',
 'commigo.»--«Meu',
 'caro',
 'Dom',
 'Casmurro,',
 'não',
 'cuide',
 'que',
 'o',
 'dispenso',
 'do',
 'theatro',
 'amanhã;',
 'venha',
 'e',
 'dormirá',
 'aqui',
 'na',
 'cidade;',
 'dou-lhe',
 'camarote,',
 'dou-lhe',
 'chá,',
 'dou-lhe',
 'cama;',
 'só',
 'não',
 'lhe',
 'dou',
 'moça.»',
 'Não',
 'consultes',
 'diccionarios.',
 '_Casmurro_',
 'não',
 'está',
 'aqui',
 'no',
 'sentido',
 'que',
 'elles',
 'lhe',
 'dão,',
 'mas',
 'no',
 'que',
 'lhe',
 'poz',
 'o',
 'vulgo',
 'de',
 'homem',
 'calado',
 'e',
 'mettido',
 'comsigo.',
 '_Dom_',
 'veiu',
 'por',
 'ironia,',
 'para',
 'attribuir-me',
 'fumos',
 'de',
 'fidalgo.',
 'Tudo',
 'por',
 'estar',
 'cochilando!',
 'Tambem',
 'não',
 'achei',
 'melhor',
 'titulo',
 'para',
 'a',
 'minha',
 'narração;',
 'se',
 'não',
 'tiver',
 'outro',
 "d'aqui",
 'até',
 'ao',
 'fim',
 'do',
 'livro,',
 'vae',
 'este',
 'mesmo.',
 'O',
 'meu',
 'poeta',
 'do',
 'trem',
 'ficará',
 'sabendo',
 'que',
 'não',
 'lhe',
 'guardo',
 'rancor.',
 'E',
 'com',
 'pequeno',
 'esforço,',
 'sendo',
 'o',
 'titulo',
 'seu,',
 'poderá',
 'cuidar',
 'que',
 'a',
 'obra',
 'é',
 'sua.',
 'Ha',
 'livros',
 'que',
 'apenas',
 'terão',
 'isso',
 'dos',
 'seus',
 'autores;',
 'alguns',
 'nem',
 'tanto.',
 'II.',
 'Do',
 'livro.',
 'Agora',
 'que',
 'expliquei',
 'o',
 'titulo,',
 'passo',
 'a',
 'escrever',
 'o',
 'livro.',
 'Antes',
 'disso,',
 'porém,',
 'digamos',
 'os',
 'motivos',
 'que',
 'me',
 'põem',
 'a',
 'penna',
 'na',
 'mão.',
 'Vivo',
 'só,',
 'com',
 'um',
 'creado.',
 'A',
 'casa',
 'em',
 'que',
 'moro',
 'é',
 'propria;',
 'fil-a',
 'construir',
 'de',
 'proposito,',
 'levado',
 'de',
 'um',
 'desejo',
 'tão',
 'particular',
 'que',
 'me',
 'vexa',
 'imprimil-o,',
 'mas',
 'vá',
 'lá.',
 'Um',
 'dia,',
 'ha',
 'bastantes',
 'annos,',
 'lembrou-me',
 'reproduzir',
 'no',
 'Engenho',
 'Novo',
 'a',
 'casa',
 'em',
 'que',
 'me',
 'criei',
 'na',
 'antiga',
 'rua',
 'de',
 'Matacavallos,',
 'dando-lhe',
 'o',
 'mesmo',
 'aspecto',
 'e',
 'economia',
 'daquella',
 'outra,',
 'que',
 'desappareceu.',
 'Constructor',
 'e',
 'pintor',
 'entenderam',
 'bem',
 'as',
 'indicações',
 'que',
 'lhes',
 'fiz:',
 'é',
 'o',
 'mesmo',
 'predio',
 'assobradado,',
 'tres',
 'janellas',
 'de',
 'frente,',
 'varanda',
 'ao',
 'fundo,',
 'as',
 'mesmas',
 'alcovas',
 'e',
 'salas.',
 'Na',
 'principal',
 'destas,',
 'a',
 'pintura',
 'do',
 'tecto',
 'e',
 'das',
 'paredes',
 'é',
 'mais',
 'ou',
 'menos',
 'egual,',
 'umas',
 'grinaldas',
 'de',
 'flores',
 'miudas',
 'e',
 'grandes',
 'passaros',
 'que',
 'as',
 'tomam',
 'nos',
 'bicos,',
 'de',
 'espaço',
 'a',
 'espaço.',
 'Nos',
 'quatro',
 'cantos',
 'do',
 'tecto',
 'as',
 'figuras',
 'das',
 'estações,',
 'e',
 'ao',
 'centro',
 'das',
 'paredes',
 'os',
 'medalhões',
 'de',
 'Cesar,',
 'Augusto,',
 'Nero',
 'e',
 'Massinissa,',
 'com',
 'os',
 'nomes',
 'por',
 'baixo...',
 'Não',
 'alcanço',
 'a',
 'razão',
 'de',
 'taes',
 'personagens.',
 'Quando',
 'fomos',
 'para',
 'a',
 'casa',
 'de',
 'Matacavallos,',
 'já',
 'ella',
 'estava',
 'assim',
 'decorada;',
 'vinha',
 'do',
 'decennio',
 'anterior.',
 'Naturalmente',
 'era',
 'gosto',
 'do',
 'tempo',
 'metter',
 'sabor',
 'classico',
 'e',
 'figuras',
 'antigas',
 'em',
 'pinturas',
 'americanas.',
 'O',
 'mais',
 'é',
 'tambem',
 'analogo',
 'e',
 'parecido.',
 'Tenho',
 'chacarinha,',
 'flôres,',
 'legume,',
 'uma',
 'casuarina,',
 'um',
 'poço',
 'e',
 'lavadouro.',
 'Uso',
 'louça',
 'velha',
 'e',
 'mobilia',
 'velha.',
 'Emfim,',
 'agora,',
 'como',
 "outr'ora,",
 'ha',
 'aqui',
 'o',
 'mesmo',
 'contraste',
 'da',
 'vida',
 'interior,',
 'que',
 'é',
 'pacata,',
 'com',
 'a',
 'exterior,',
 'que',
 'é',
 'ruidosa.',
 'O',
 'meu',
 'fim',
 'evidente',
 'era',
 'atar',
 'as',
 'duas',
 'pontas',
 'da',
 'vida,',
 'e',
 'restaurar',
 'na',
 'velhice',
 'a',
 'adolescencia.',
 'Pois,',
 'senhor,',
 'não',
 'consegui',
 'recompor',
 'o',
 'que',
 'foi',
 'nem',
 'o',
 'que',
 'fui.',
 'Em',
 'tudo,',
 'se',
 'o',
 'rosto',
 'é',
 'egual,',
 'a',
 'physionomia',
 'é',
 'differente.',
 'Se',
 'só',
 'me',
 'faltassem',
 'os',
 'outros,',
 'vá;',
 'um',
 'homem',
 'consola-se',
 'mais',
 'ou',
 'menos',
 'das',
 'pessoas',
 'que',
 'perde;',
 'mas',
 'falto',
 'eu',
 'mesmo,',
 'e',
 'esta',
 'lacuna',
 'é',
 'tudo.',
 'O',
 'que',
 'aqui',
 'está',
 'é,',
 'mal',
 'comparando,',
 'semelhante',
 'á',
 'pintura',
 'que',
 'se',
 'põe',
 'na',
 'barba',
 'e',
 'nos',
 'cabellos,',
 'e',
 'que',
 'apenas',
 'conserva',
 'o',
 'habito',
 'externo,',
 'como',
 'se',
 'diz',
 'nas',
 'autopsias;',
 'o',
 'interno',
 'não',
 'aguenta',
 'tinta.',
 'Uma',
 'certidão',
 'que',
 'me',
 'desse',
 'vinte',
 'annos',
 'de',
 'edade',
 'poderia',
 'enganar',
 'os',
 'extranhos,',
 'como',
 'todos',
 'os',
 'documentos',
 'falsos,',
 'mas',
 'não',
 'a',
 'mim.',
 'Os',
 'amigos',
 'que',
 'me',
 'restam',
 'são',
 'de',
 'data',
 'recente;',
 'todos',
 'os',
 'antigos',
 'foram',
 'estudar',
 'a',
 'geologia',
 'dos',
 'campos',
 'santos.',
 'Quanto',
 'ás',
 'amigas,',
 'algumas',
 'datam',
 'de',
 'quinze',
 'annos,',
 'outras',
 'de',
 'menos,',
 'e',
 'quasi',
 'todas',
 'creem',
 'na',
 'mocidade.',
 'Duas',
 'ou',
 'tres',
 'fariam',
 'crer',
 'nella',
 'aos',
 'outros,',
 'mas',
 'a',
 'lingua',
 'que',
 'falam',
 'obriga',
 'muita',
 'vez',
 'a',
 'consultar',
 'os',
 'diccionarios,',
 'e',
 'tal',
 'frequencia',
 'é',
 'cançativa.',
 'Entretanto,',
 'vida',
 'differente',
 'não',
 'quer',
 'dizer',
 'vida',
 'peor;',
 'é',
 'outra',
 'cousa.',
 'A',
 'certos',
 'respeitos,',
 'aquella',
 'vida',
 'antiga',
 'apparece-me',
 'despida',
 'de',
 'muitos',
 'encantos',
 'que',
 'lhe',
 'achei;',
 'mas',
 'é',
 'tambem',
 'exacto',
 'que',
 'perdeu',
 'muito',
 'espinho',
 'que',
 'a',
 'fez',
 'molesta,',
 'e,',
 'de',
 'memoria,',
 'conservo',
 'alguma',
 'recordação',
 'doce',
 'e',
 'feiticeira.',
 'Em',
 'verdade,',
 'pouco',
 'appareco',
 'e',
 'menos',
 'falo.',
 'Distracções',
 'raras.',
 'O',
 'mais',
 'do',
 'tempo',
 'é',
 'gasto',
 'em',
 'hortar,',
 'jardinar',
 'e',
 'ler;',
 'como',
 'bem',
 'e',
 'não',
 'durmo',
 'mal.',
 'Ora,',
 'como',
 'tudo',
 'cança,',
 'esta',
 'monotonia',
 'acabou',
 'por',
 'exhaurir-me',
 'tambem.',
 'Quiz',
 'variar,',
 'e',
 'lembrou-me',
 'escrever',
 'um',
 'livro.',
 'Jurisprudencia,',
 'philosophia',
 'e',
 'politica',
 'acudiram-me,',
 'mas',
 'não',
 'me',
 'acudiram',
 'as',
 'forças',
 'necessarias.',
 'Depois,',
 'pensei',
 'em',
 'fazer',
 'uma',
 '_Historia',
 'dos',
 'Suburbios_,',
 'menos',
 'secca',
 'que',
 'as',
 'memorias',
 'do',
 'padre',
 'Luiz',
 'Gonçalves',
 'dos',
 'Santos,',
 'relativas',
 'á',
 'cidade;',
 'era',
 'obra',
 'modesta,',
 'mas',
 'exigia',
 'documentos',
 'e',
 'datas,',
 'como',
 'preliminares,',
 'tudo',
 'arido',
 'e',
 'longo.',
 'Foi',
 'então',
 'que',
 'os',
 'bustos',
 'pintados',
 'nas',
 'paredes',
 'entraram',
 'a',
 'falar-me',
 'e',
 'a',
 'dizer-me',
 'que,',
 'uma',
 'vez',
 'que',
 'elles',
 'não',
 'alcançavam',
 'reconstituir-me',
 'os',
 'tempos',
 'idos,',
 'pegasse',
 'da',
 'penna',
 'e',
 'contasse',
 'alguns.',
 'Talvez',
 'a',
 'narração',
 'me',
 'désse',
 'a',
 'illusão,',
 'e',
 'as',
 'sombras',
 'viessem',
 'perpassar',
 'ligeiras,',
 'como',
 'ao',
 'poeta,',
 'não',
 'o',
 'do',
 'trem,',
 'mas',
 'o',
 'do',
 '_Fausto:',
 'Ahi',
 'vindes',
 'outra',
 'vez,',
 'inquietas',
 'sombras...?_',
 'Fiquei',
 'tão',
 'alegre',
 'com',
 'esta',
 'ideia,',
 'que',
 ...]

In [ ]:
#Criar um dataframe da lista criada

tabela = pd.DataFrame({'palavras': palavras})
tabela

       palavras
0           DOM
1      CASMURRO
2           POR
3       MACHADO
4            DE
...         ...
65702         É
65703      bem,
65704         e
65705         o
65706    resto?

[65707 rows x 1 columns]

In [ ]:
#Classificar as palavras mais usadas

palavras_mais_usadas = tabela['palavras'].value_counts()

palavras_mais_usadas.head(20)

palavras
que     2519
a       2258
e       2001
de      1938
o       1527
não     1152
um       707
da       622
do       618
é        618
os       614
para     531
com      522
se       514
me       489
as       488
mas      481
era      445
em       419
eu       416
Name: count, dtype: int64

In [ ]:
#Retirar a ultima palavra da lista criando outra coluna, assim entendemos como funcionado uma IA generativa

tabela['proxima_palavra'] = tabela['palavras'].shift(-1)

tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?
65706    resto?             NaN

[65707 rows x 2 columns]

In [ ]:
#Retirar valores nulos 

tabela = tabela.dropna()

tabela

       palavras proxima_palavra
0           DOM        CASMURRO
1      CASMURRO             POR
2           POR         MACHADO
3       MACHADO              DE
4            DE           ASSIS
...         ...             ...
65701   CXLVIII               É
65702         É            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [ ]:
#Selecionar uma palavra do txt

filtro = tabela['palavras'] == 'feliz'

In [ ]:
#Mostra quantas vezes aparece no texto

tabela[filtro]['palavras'].value_counts()

palavras
feliz    2
Name: count, dtype: int64

In [ ]:
# Conta quantas vezes a proxima palavra aparece a partir da palavra escolhida

tabela[filtro]['proxima_palavra'].value_counts()

proxima_palavra
com    1
de     1
Name: count, dtype: int64

In [ ]:
#Probabilidade da próxima palavra aparecer

tabela[filtro]['proxima_palavra'].value_counts(normalize=True)

proxima_palavra
com    0.5
de     0.5
Name: proportion, dtype: float64

In [ ]:
#Filtrar a palavra com maior probabilidade de ser a proxima

tabela[filtro]['proxima_palavra'].value_counts().idxmax()

'com'

In [93]:
filtro = tabela['palavras'] == 'feliz'

tabela[filtro]

      palavras proxima_palavra
21300    feliz             com
45334    feliz              de